name: Deploy to PyPI

on: [push]

jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Install Twine
          run: pip install twine
          
        - name: Deploy to PyPI
          run: twine upload dist/*
          env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
