name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
        pip install -r requirements.txt

    - name: Test with pytest
      run: poetry run pytest

    - name: Install coverage
      run: |
        pip install coverage

    - name: Run Tests with Coverage > 90%
      run: |
        coverage run -m pytest tests/
        coverage report -m --fail-under=90

    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run flake8
      run: flake8 .

    - name: Check docstrings
      run: |
        pip install pydocstyle
        pydocstyle .
    
    - name: safety
      run: |
        pip install safety
        pip install --upgrade setuptools
        safety check